export const darkTheme = {
  bg: "#212121",
  bgLighter: "#202020",
  bgHover: "#3d3c3c",
  bgIcon: "white",
  bgHamburger: "#dddddd",
  bgPlaceHolder: "#161616",
  bgSetting: "  #585858",
  bgPlaceHolderColor: "white",
  bgSearchButton: "#3d3c3c",
  text: "white",
  textSoft: "#aaaaaa",
  soft: "#373737",
  textDesc: "#9d9c9c",
};
export const lightTheme = {
  bg: "white",
  bgLighter: "white",
  bgHover: "#e9e6e6",
  bgIcon: "black",
  bgHamburger: "black",
  bgPlaceHolder: "#f9f9f9",
  bgSetting: "#f9f9f9",
  bgPlaceHolderColor: "black",
  bgSearchButton: "#e9e6e6",
  text: "black",
  textSoft: "#606060",
  soft: "#eeebeb",
  textDesc: "#8f8e8e",
};
